# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf2a967f584814db5a1586dc3fb4aa915fcbaf2133fea5eaf891bdbc98bd9de3f45993e1e83ac3099706a48f5745503b1e18a5d5af3226c5100891b40d65788e

test:
  secret_key_base: 958a4d6259431a4122b1ca000e5ba2f0641d2481a0a3c852758518619856b68b539f0300471e16fdb9e2ad3fa7275ce0c79cb9f38e04eca21dc9cf701a21fae7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
